-- Core normalized schema for DMS PostgreSQL
create table if not exists users(id uuid primary key, username varchar(80) unique not null, email varchar(256) unique not null, password_hash text not null, role int not null, is_active boolean not null default true);
create table if not exists distributors(id uuid primary key, code varchar(40) unique not null, name varchar(200) not null, zone varchar(40) not null, credit_limit numeric(18,2) not null default 0, outstanding_amount numeric(18,2) not null default 0, is_active boolean not null default true);
create table if not exists items(id uuid primary key, item_code varchar(40) unique not null, name varchar(200) not null, unit varchar(20) not null, "group" varchar(60) not null, attribute varchar(60) not null, moq numeric(18,2) not null default 0, base_price numeric(18,2) not null default 0);
create table if not exists stock(id uuid primary key, distributor_id uuid not null references distributors(id), item_id uuid not null references items(id), quantity numeric(18,2) not null, reorder_level numeric(18,2) not null, unique(distributor_id,item_id));
create table if not exists orders(id uuid primary key, order_number varchar(40) unique not null, distributor_id uuid not null references distributors(id), order_date date not null, status varchar(30) not null, gross_amount numeric(18,2) not null, discount_amount numeric(18,2) not null, net_amount numeric(18,2) not null);
create table if not exists order_items(id uuid primary key, order_id uuid not null references orders(id), item_id uuid not null references items(id), quantity numeric(18,2) not null, rate numeric(18,2) not null, line_gross numeric(18,2) not null, discount_amount numeric(18,2) not null, line_net numeric(18,2) not null, free_quantity numeric(18,2) not null, cashback_amount numeric(18,2) not null, points numeric(18,2) not null);
create table if not exists invoices(id uuid primary key, invoice_number varchar(40) unique not null, distributor_id uuid not null references distributors(id), order_id uuid not null references orders(id), invoice_date date not null, amount numeric(18,2) not null, sync_status varchar(20) not null);
create table if not exists claims(id uuid primary key, distributor_id uuid not null references distributors(id), claim_type varchar(50) not null, amount numeric(18,2) not null, status varchar(20) not null, reason text not null);
create table if not exists schemes(id uuid primary key, name varchar(120) not null, scheme_type varchar(20) not null, apply_on varchar(20) not null, calculation_mode varchar(20) not null, status varchar(20) not null, valid_from date not null, valid_to date not null, item_id uuid null references items(id), item_group varchar(60), attribute varchar(60));
create table if not exists scheme_slabs(id uuid primary key, scheme_id uuid not null references schemes(id), min_qty numeric(18,2) not null, max_qty numeric(18,2), min_value numeric(18,2) not null, max_value numeric(18,2), discount_percent numeric(18,2) not null, free_qty numeric(18,2) not null, cashback_amount numeric(18,2) not null, points numeric(18,2) not null);
create table if not exists replenishment(id uuid primary key, distributor_id uuid not null references distributors(id), item_id uuid not null references items(id), current_stock numeric(18,2) not null, suggested_qty numeric(18,2) not null, status varchar(20) not null);
